style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/umotif-public/terraform-aws-backup
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject